### PR TITLE
Bugfixes and feature updates

### PR DESCRIPTION
**Pull request by astewart-xmos**
Place-holder PR for the work I'm actively engaged in.

I had a request for #95 to be merged and closed, so I'm picking up here where I left off there.

- [x] #88
- [x] #72
- [x] #73
- [x] #74
- [x] #75
- [x] #90
- [x] #91
- [x] #92
- [ ] #94
- [x] #96
- [x] #97
- [x] #102

### CODE REVIEW

**Comment by astewart-xmos** [comment]
I've made a big commit with trig functions, exponentials and logarithms, but x86 implementations are still needed for many of the low-level functions.

**Comment by astewart-xmos** [comment]
I've pushed changes for #72, but I want to note here that it does not include arcsin(), arccos(), arctan(), sinh() or cosh().  I still want to add those, but the various versions of tan(), log(), exp() and logistic() ended up taking much longer than I expected. Hopefully I'll come back to the others at some point, if they're needed.

**Comment by astewart-xmos** [comment]
I decided against doing anything with #91 for this PR. It's been subsumed by #103 which calls for a broader refactoring of the library.

**Review by keithm-xmos — APPROVED** [review]
Rubber stamp approval

**Pull request merged**
